CREATE TABLE DEPARTMENT(
    DEPT_NAME VARCHAR2(15),
    BUILDING VARCHAR(30) ,
    BUDGET NUMBER,
    CONSTRAINT DEPT_NAME_PK PRIMARY KEY (DEPT_NAME),
    CONSTRAINT BUDGET_CHECK CHECK (BUDGET>0)
     
);
CREATE TABLE COURSE(
    COURSE_ID VARCHAR2(10),
    TITLE VARCHAR2(30),
    DEPT_NAME VARCHAR(30),
    CREDITS NUMBER ,
    CONSTRAINT C_ID_PK1 PRIMARY KEY (COURSE_ID),
    CONSTRAINT DPT_NM_FK1 FOREIGN KEY (DEPT_NAME) REFERENCES DEPARTMENT(DEPT_NAME) ON DELETE CASCADE,
    CONSTRAINT CREDIT_CHK1 CHECK(CREDITS>=1)
   
   

);


INSERT INTO DEPARTMENT  VALUES ('CSE','AB3',1500);
INSERT INTO DEPARTMENT  VALUES ('BBA','AB3',20000);
INSERT INTO DEPARTMENT  VALUES ('ME','FUB',25000);

SELECT * FROM DEPARTMENT;

INSERT INTO COURSE  VALUES ('CSE101','COMPUTER FUNDAMENTAL','CSE',4);
INSERT INTO COURSE  VALUES ('MKT101','BUSSINESS FUNDAMENTAL','BBA',3);
INSERT INTO COURSE  VALUES ('ME103','MECHANICAL FUNDAMENTAL','ME',2);

SELECT * FROM MYSUBJECT;

ALTER TABLE DEPARTMENT ADD CHAIRPERSON VARCHAR2(20);

UPDATE DEPARTMENT SET CHAIRPERSON = 'MAHIN ISLAM ' WHERE DEPT_NAME = 'CSE';
UPDATE DEPARTMENT SET CHAIRPERSON = 'TT' WHERE DEPT_NAME = 'ME';
UPDATE DEPARTMENT SET CHAIRPERSON = 'DR. FARHANA' WHERE DEPT_NAME = 'BBA';


ALTER TABLE COURSE RENAME  TO MYSUBJECT;  
-- CROSS JOIN + CONDITION
SELECT * FROM DEPARTMENT , COURSE WHERE DEPARTMENT.DEPT_NAME = COURSE.DEPT_NAME;
--NATURANL JOIN
SELECT * FROM DEPARTMENT NATURAL JOIN COURSE;